
spring:
  datasource: 
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:fscompdb
    data-username: sa
    data-password: 
  application:  
    name: rsa-encrypt-decrypt
    
server:
  port: 8080
  servlet:
    context-path: /rest-api
    
logging:
 config: classpath:log4j.xml
 file: rest-api.log
 path: /opt/logs
  
